#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

//no wiec: wiadomo, dolaczamy pliki z funckjami





/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

//#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
//#include <wx/colourdata.h>
//#include <wx/colordlg.h>
#include <wx/msgdlg.h>
#include <wx/filedlg.h>
#include <memory>

#include "sup_classes.hpp"


/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
protected:
	// Handlers for MyFrame1 events.

	void MainFormClose(wxCloseEvent& event); //formalnosc
	void Panel_Repaint(wxUpdateUIEvent& event); //chyba formalnosc
	void click_button_load(wxCommandEvent& event); //formalnosc
	//tu reszta zalezy pewnie od nazw zmiennych ktore sa uzyte w funkcjach/klasach
	void Wage_1_Update(wxCommandEvent& event);
	void Wage_2_Update(wxCommandEvent& event);
	void Wage_3_Update(wxCommandEvent& event);
	void Wage_4_Update(wxCommandEvent& event);
	void Angle_Update(wxCommandEvent& event);
	void Wages_Calculate(wxCommandEvent& event);
	void Rotate_Bitmap(wxCommandEvent& event);
	void Graph_Paint(wxUpdateUIEvent& event); //tu jeszcze nie jestem pewna, czy dobra funkcja jest uzyta

	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
	
		void Variation_Update();
		void repaint();
		void repaint_graph();

private:
	ImageHolder image;
	wxImage graph;

	std::shared_ptr<wxFileDialog> m_file_dialog;
	
};

#endif // __GUIMyFrame1__
